apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-sri
  labels:
    app: sriapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sriapp
  template:
    metadata:
      labels:
        app: sriapp
    spec:
      containers:
      - name: container-sriapp
        image: srikanta1219/sri-app:
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sriapp-svc
  labels:
    app: sriapp
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: sriapp
